#pragma once


typedef enum Shader {
    SHADER_VERTEX_POSITION_COLOR_2D,
    SHADER_VERTEX_POSITION_COLOR,
    SHADER_VERTEX_POSITION_TEXTURE,
    SHADER_VERTEX_TEXT,
    SHADER_VERTEX_SHADOW_DEPTH,
    SHADER_VERTEX_POST_PROCESSING,
    SHADER_VERTEX_BILLBOARD,
    SHADER_VERTEX_LINE,
    SHADER_VERTEX_PARTICLE,
    SHADER_FRAGMENT_SOLID_COLOR,
    SHADER_FRAGMENT_SOLID_COLOR_DEPTH,
    SHADER_FRAGMENT_PHONG,
    SHADER_FRAGMENT_SHADOW_DEPTH,
    SHADER_FRAGMENT_TEXT,
    SHADER_FRAGMENT_POST_PROCESSING,
    SHADER_FRAGMENT_DEPTH_OF_FIELD,
    SHADER_FRAGMENT_PARTICLE,
    SHADER_COUNT
} Shader;


typedef enum {
    PIPELINE_2D,
    PIPELINE_TEXT,
    PIPELINE_3D,
    PIPELINE_3D_TEXTURED,
    PIPELINE_SHADOW_DEPTH,
    PIPELINE_POST_PROCESSING,
    PIPELINE_DEPTH_OF_FIELD,
    PIPELINE_BILLBOARD,
    PIPELINE_LINE,
    PIPELINE_PARTICLE,
    PIPELINE_COUNT
} Pipeline;


SDL_GPUGraphicsPipeline* pipelines[PIPELINE_COUNT];


void load_shaders(void);

void create_pipelines(void);

void destroy_pipelines(void);
